# Generated by Django 4.2.27 on 2025-12-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, null=True)),
                ('services_provided', models.TextField(blank=True, help_text='Services Provided', null=True)),
                ('areas_served', models.TextField(blank=True, help_text='Areas Served', null=True)),
                ('professional_information', models.TextField(blank=True, help_text='Professional Information', null=True)),
                ('category', models.CharField(blank=True, help_text='Category', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('additional_addresses', models.TextField(blank=True, null=True)),
                ('typical_job_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('followers', models.CharField(blank=True, max_length=100, null=True)),
                ('socials', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
                'db_table': 'designers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, help_text='Project thumbnail image', max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.CharField(blank=True, help_text='Number of photos as string', max_length=50, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('image_count', models.IntegerField(default=0, help_text='Total number of images in this project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(help_text='Designer who created this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.designer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='projects_project_e2329d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['designer', '-created_at'], name='projects_designe_e83954_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_id'], name='images_image_i_9be874_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['project', '-created_at'], name='images_project_4245e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('project', 'image_id')},
        ),
    ]
